console.log("products.js");
const allProducts = [
  {
    id: 1,
    name: "High-Back Bench",
    price: "9.99",
    img: "./all-product-images/high-back-bench.jpg",
    brand: "ikea",
  },
  {
    id: 2,
    name: "Albany Table",
    price: "79.99",
    img: "./all-product-images/albany-table.jpg",
    brand: "marcos",
  },
  {
    id: 3,
    name: "Accent Chair",
    price: "25.99",
    img: "./all-product-images/accent-chair.jpg",
    brand: "caressa",
  },
  {
    id: 4,
    name: "Wooden Table",
    price: "45.99",
    img: "./all-product-images/wooden-table.jpg",
    brand: "caressa",
  },
  {
    id: 5,
    name: "Dining Table",
    price: "6.99",
    img: "./all-product-images/dining-table.jpg",
    brand: "caressa",
  },
  {
    id: 6,
    name: "Sofa Set",
    price: "69.99",
    img: "./all-product-images/sofa-set.jpg",
    brand: "liddy",
  },
  {
    id: 7,
    name: "Modern Bookshelf",
    price: "8.99",
    img: "./all-product-images/modern-bookshelf.jpg",
    brand: "marcos",
  },
  {
    id: 8,
    name: "Emperor Bed",
    price: "21.99",
    img: "./all-product-images/emperor-bed.jpg",
    brand: "liddy",
  },
  {
    id: 9,
    name: "Utopia Sofa",
    price: "39.95",
    img: "./all-product-images/utopia-sofa.jpg",
    brand: "marcos",
  },
  {
    id: 10,
    name: "Entertainment Center",
    price: "29.98",
    img: "./all-product-images/entertainment-center.jpg",
    brand: "liddy",
  },
  {
    id: 11,
    name: "Albany Sectional",
    price: "10.99",
    img: "./all-product-images/albany-sectional.jpg",
    brand: "ikea",
  },
  {
    id: 12,
    name: "Leather Sofa",
    price: "$9.99",
    img: "./all-product-images/leather-sofa.jpg",
    brand: "liddy",
  },
];
